### ISSUE TITLE
libevent: Segfault on tests/module-system- event.js

### ISSUE THREAD

**Issue by sebastien** [sebastien/k7#8]
With latest version of K7, I get a segfault when executing

 ./k7 tests/module-system- event.js  
 bound!

 event added fd 5
 yep,added

 expected err: Error: Operation now in progress

 connected

 event added fd 6 
 Uncaught exception: Error: Invalid argument
 Segmentation fault

With gdb output

 [Switching to Thread 0xb796f6f0 (LWP 30101)]
 0xb7ce6613 in strlen () from /lib/tls/i686/cmov/libc.so.6
 (gdb) backtrace 
 #0  0xb7ce6613 in strlen () from /lib/tls/i686/cmov/libc.so.6
 #1  0x08066264 in v8::String::New ()
 #2  0xbfd8d1ec in ?? ()
 #3  0x08076441 in v8::internal::Builtin_HandleApiCall ()
 #4  0x00000001 in ?? ()
 Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by sebastien** [comment]
Now the module was moved to tests/module-core-concurrency-libevent-base.js  and the result is :

```
$ k7 tests/module-core-concurrency-libevent-base.js
bound!

event added fd 6
yep,added

expected err: Error: Operation now in progress

connected

event added fd 7
Uncaught exception: Error: Invalid argument
Segmentation fault
```
